<div id="menu">
    <div id = "button"></div>
</div>

<div id="parallax">


    <div id = "group_1" class="parallax__group">
        <div class="parallax__layer parallax__layer--back"></div>
        <div class="parallax__layer parallax__layer--base">
            <h1>material design,<br>
                from another angle</h1>
            <p>
                Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna<br> aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
            </p>

        </div>
    </div>

    <div id = "group_2">
        <div class="parallax__layer parallax__layer--back"></div>
        <div class="parallax__layer parallax__layer--base">
            <h1>portfolio</h1>
            <div id = "slider-content">
                <div id="portfolio">

                    <div id = "slider">
                        <div class="portfolio-site"><img src="http://site.my/img/site-1.PNG"></div>
                        <div class="portfolio-site"><img src="http://site.my/img/site-1.PNG"></div>
                        <div class="portfolio-site"><img src="http://site.my/img/site-1.PNG"></div>
                        <div class="portfolio-site"><img src="http://site.my/img/site-1.PNG"></div>
                        <div class="portfolio-site"><img src="http://site.my/img/site-1.PNG"></div>
                    </div>

                </div>
                <div id="slider-buttons">
                    <div class="slider-button" onclick="slider('1')"></div>
                    <div class="slider-button" onclick="slider('2')"></div>
                    <div class="slider-button" onclick="slider('3')"></div>
                    <div class="slider-button" onclick="slider('4')"></div>
                    <div class="slider-button" onclick="slider('5')"></div>
                </div>
            </div>
            <div class="home-button">Read more</div>
        </div>
    </div>

    <div id = "group_3" class="parallax__group">
        <div class="parallax__layer parallax__layer--back"></div>
        <div class="parallax__layer parallax__layer--base">
            <div id="skills">
                <h1>about</h1>
                <p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                <div class="skill"><img src="http://site.my/img/HTML5.png"></div>
                <div class="skill"><img src="http://site.my/img/JS.png"></div>
                <div class="skill"><img src="http://site.my/img/CSS3.png"></div>
                <div class="home-button">Read more</div>
            </div>

        </div>
    </div>




</div>
<div id="top"></div>
